BEGIN;

  TRUNCATE
  bestiary,
  users,
  campaigns,
  encounters,
  characters
  RESTART IDENTITY CASCADE;

INSERT INTO bestiary
  (monstername,type,ac,maxhp,speed,burrowspeed,climbspeed,flyspeed,swimspeed,str,strmod,dex,dexmod,con,conmod,int,intmod,wis,wismod,cha,chamod,savingthrows,skills,vulnerabilities,resistances,immunities,senses,languages,cr,xp,extras,actions)
VALUES
  ('Aarakocra',
  'Medium humanoid, neutral good',
  12,
  '3d8',
  20,
  null,
  null,
  50,
  null,
  10,
  0,
  14,
  2,
  10,
  0,
  11,
  0,
  12,
  1,
  11,
  0,
  null,
  'Perception +5',
  null,
  null,
  null,
  'passive Perception 15',
  'Auran',
  0.25,
  50,
  ARRAY[['Dive Attack', 'If the aarakocra if flying and dives at least 30 ft straight toward a target and then hits it with a melee weapon attack, the attack deals an extra (1d6) damage to the target.']],
  ARRAY[['Talon','Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit:(1d4+2) slashing damage']]),

  ('Aboleth',
  'Large aberration, lawful evil',
  '17 (natural armor)',
  '18d10 + 36',
  10,
  null,
  null,
  null,
  40,
  21,
  5,
  9,
  -1,
  15,
  2,
  18,
  4,
  15,
  2,
  18,
  4,
  'Con +6, Int +8, Wis +6',
  'History +12, Perception +10',
  null,
  null,
  null,
  'Darkvision 120ft, passive Perception 20',
  'Deep Speech, telepathy 120 ft.',
  10,
  5900,
  ARRAY[['Amphibious','The aboleth can breathe air and water'], ['Mucous Cloud','While underwater, the aboleth is surrounded by ransformative mucus. A creature that touches the aboleth or that hits it with a melee attack while within 5 feet of it must make a DC 14 Constitution saving throw. On a failure, the creature is deseased for (1d4) hours. The diseased creature can breath only underwater'], ['Probing Telepathy','If a creature communicates telepathically with the aboleth, the aboleth learns the creature''s greatest desires if the aboleth can see the creature.']],
  ARRAY[['Multiattack','The aboleth makes three tentacle attacks.'], ['Tentacle','Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: (2d6+5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased. The disease has no effect for 1 minute and can be removed by any magic that cures disease. After 1 minute, the diseased creature''s skin becomes translucent and slimy, the creature can''t regain hit points unless it is underwater, and the disease can be removed only by heal or another di sease-curing spell of 6th level or higher. When the creature is outside a body of water, it takes (1d12) acid damage every 10 minutes unless moisture is applied to the skin before 10 minutes have passed.'], ['Tail','Melee Weapon Attack: +9 to hit, reach 10 ft. one target. Hit: (3d6 + 5) bludgeoning damage.'], ['Enslave (3/Day)','The aboleth targets one creature it can see within 3 feet of it. The target must succeed on a DC 14 Wisdom saving throw or be magically charmed by the aboleth until the abolthe dies or until it is on a different plane of existence from the target. The charmed target is under the aboleth''s control and can''t take reactions, and the aboleth and the target can communicate telepathically with each other over any distance'], ['Legendary Actions','The aboleth can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature''s turn . The aboleth regains spent legendary actions at the start of its turn. --Detect: The aboleth makes a Wisdom (Perception) check. --Tail Swipe: The aboleth makes one tail attack. --Psychic Drain (Costs 2 Actions): One creature charmed by the aboleth takes (3d6) psychic damage, and the aboleth regains hit points equal to the damage the creature takes.']]),

  ('Deva',
  'Medium celestial, lawful good',
  '17 (natural armor)',
  '16d8 + 64',
  30,
  null,
  null,
  90,
  null,
  18,
  4,
  18,
  4,
  18,
  4,
  17,
  3,
  20,
  5,
  20,
  5,
  'Wis +9, Cha +9',
  'Insight +7, Perception +9',
  null,
  'radiant; bludgeoning, piercing, and slashing from nonmagical weapons',
  'charmed, exhaustion, frightened',
  'darkvision 120 ft., passive Perception 19',
  'all, telepathy 120 ft',
  10,
  5900,
  ARRAY[['Angelic Weapons','The deva''s weapon attacks are magical. When the deva hits with any weapon, the weapon deals an extra (4d8) radiant damage (included in the attack)'], ['Innate Spellcasting','The deva''s spellcasting ability is Charisma (spell save DC 17). The deva can innately cast the following spells, requiring only verbal components: At will:'], ['Magic Resistance','The deva has advantage on saving throws against spells and other magical effects.']],
  ARRAY[['Multiattack', 'The deva makes two melee attacks.'], ['Mace', 'Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: (1d6 + 4) bludgeoning damage plus (4d8) radiant damage.'], ['Healing Touch (3/Day)', 'The deva touches another creature. The target magically regains (4d8 + 2) hit points and is freed from any curse, disease, poison, blindness, or deafness.'], ['Change Shape', 'The deva magically polymorphs into a humanoid or beast that has a challenge rating equal to or less than its own, or back into its true form. It reverts to its true form if it dies. Any equipment it is wearing or carrying is absorbed or borne by the new form (the deva''s choice). In a new form, the deva retains its game statistics and ability to speak, but its AC, movement modes, Strength, Dexterity, and special senses are replaced by those of the new form, and it gains any statistics and capabilities (except class features, legendary actions, and lair actions) that the new form has but that it lacks.']]),

  ('Planetar',
  'Large celestial, lawful good',
  '19 (natural armor)',
  '16d10 + 112',
  40,
  null,
  null,
  120,
  null,
  24,
  7,
  20,
  5,
  24,
  7,
  19,
  4,
  22,
  6,
  25,
  7,
  'Con +12, Wis +11, Cha+12',
  'Perception +11',
  null,
  'radiant; bludgeoning, piercing, and slashing from non-magical weapons',
  'charmed, exhaustion, frightened',
  'Truesight 120 ft., passive Perception 21',
  'all, telepathy 120 ft.',
  16,
  15000,
  ARRAY[['Angelic Weapons','The planetar''s weapon attacks are magical. When the planetar hits with any weapon, the weapon deals an extra (5d8) radiant damage (included in the attack).'], ['Divine Awareness','The planetar knows if it hears a lie'], ['Innate Spellcasting','The planetar''s spellcasting ability is Charisma (spell save DC 20). The planetar can innately cast the following spells, requiring no material components: --At will: detect evil and good, invisibility (self only) --3/day each: blade barrier, dispel evil and good, flame strike, raise dead --1/day each: commune, control weather, insect plague'], ['Magic Resistance','The planetar has advantage on saving throws against spells and other magical effects.']],
  ARRAY[['Multiattack','The planetar makes two melee attacks'], ['Greatsword','Melee Weapon Attack: +12 to hit, reach 5 ft., one target. Hit: (4d6 + 7) slashing damage plus (5d8) radiant damage'], ['Healing Touch (4/Day)','The planetar touches another creature. The target magically regains (6d8 + 3) hit points and is freed from any curse, disease, poison, blindness, or deafness']]),

  ('Solar',
  'Large celestial, lawful good',
  '21 (natural armor)',
  '18d10 + 144',
  50,
  null,
  null,
  150,
  null,
  26,
  8,
  22,
  6,
  26,
  8,
  25,
  7,
  25,
  7,
  30,
  10,
  'Int +14, Wis +14, Cha +17',
  'Perception +14',
  null,
  'radiant; bludgeoning, piercing, and slashing from nonmagical weapons',
  'necrotic, poison, charmed, exhaustion, frightened, poisoned',
  'Truesight 120 ft., passive Perception 24',
  'all, telepathy 120 ft.',
  21,
  33000,
  ARRAY[['Angelic Weapons','The solar''s weapon attacks are magical. When the solar hits with any weapon, the weapon deals an extra (6d8) radiant damage (included in the attack).'], ['Divine Awareness','The planetar knows if it hears a lie'], ['Innate Spellcasting','The solar''s spellcasting ability is Charisma (spell save DC 25). It can innately cast the following spells, requiring no material components: --At will: detect evil and good, invisibility (self only) --3/day each: blade barrier, dispel evil and good, resurrection --1/day each: commune, control weather'], ['Magic Resistance','The solar has advantage on saving throws against spells and other magical effects.']],
  ARRAY[['Multiattack','The solar makes two greatsword attacks'], ['Greatsword','Melee Weapon Attack: +15 to hit, reach 5 ft., one target. Hit: (4d6 + 8) slashing damage plus (6d8) radiant damage'], ['Slaying Longbow','Ranged Weapon Attack: +13 to hit, range 120/600 ft., one target. Hit: (2d8 + 6) piercing damage plus (6d8) radiant damage. If the target is a creature that has 100 hit points or fewer, it must succeed on a DC 15 Constitution saving throw or die'], ['Flying Sword','The solar releases its greatsword to hover magically in an unoccupied space within 5 feet of it. if the solar can see the sword, the solar can mentally command it as a bonus action to fly up to 50 feet and either make one attack against a target or return to the solar''s hands. If the hovering sword is targeted by any effect, the solar is considered to be holding it. The hovering sword falls if the solar dies.'], ['Healing Touch (4/Day)','The solar touches another creature. The target magically regains (8d8 + 4) hit points and is freed from any curse, disease, poison, blindness, or deafness'], ['Legendary Actions','The solar can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature''s turn. The solar regains spent legendary actions at the start of its turn. --Teleport: The solar magically teleports, along with any equipment it is wearing or carrying, up to 120 feet to an unoccupied space it can see. --Searing Burst (Costs 2 Actions): The solar emits magical, divine energy. Each creature of its choice in a 10 -foot radius must make a DC 23 Dexterity saving throw, taking (4d6) fire damage plus (4d6) radiant damage on a fai led save, or half as much damage on a successful one. --Blinding Gaze (Costs 3 Actions): The solar targets one creature it can see within 30 feet of it. If the target can see it, the target must succeed on a DC 15 Constitution saving throw or be blinded until magic such as the lesser restoration spell removes the blindness.']]),

  ('Animated Armor',
  'Medium construct, unaligned',
  '18 (natural armor)',
  '6d8 + 6',
  25,
  null,
  null,
  null,
  null,
  14,
  2,
  11,
  0,
  13,
  1,
  1,
  -5,
  3,
  -4,
  1,
  -5,
  null,
  null,
  null,
  null,
  'poison, psychic, blinded, charmed deafened, exhaustion, frightened, paralyzed, petrified, poisoned',
  'Blindsight 60 ft. (blind beyond this radius), passive Perception 6',
  'None',
  1,
  200,
  ARRAY[['Antimagic Susceptibility','The armor is incapacitated while in the area of an antimagic field. If targeted by dispel magic, the armor must succeed on a Constitution saving throw against the caster''s spell save DC or fall unconscious for 1 minute.'], ['False Appearance','While the armor remains motionless, it is indistinguishable from a normal suit of armor'], ['Constructed Nature','An animated object doesn''t require air, food, drink, or sleep']],
  ARRAY[['Multiattack','The armor makes two melee attacks'], ['Slam','Melee Weapon Attack: +4 to hit, reach 5ft., one target. Hit (1d6 + 2) bludgeoning damage']]),
  
  ('Flying Sword',
  'Small construct, unaligned',
  '17 (natural armor)',
  '5d6',
  0,
  null,
  null,
  50,
  null,
  12,
  1,
  15,
  2,
  11,
  0,
  1,
  -5,
  5,
  -3,
  1,
  -5,
  'Dex +4',
  null,
  null,
  null,
  'poison, psychic, blinded, charmed, deafened, frightened, paralyzed, petrified, poisoned',
  'Blindsight 60 ft. (blind beyond this radius)',
  'None',
  0.25,
  50,
  ARRAY[['Antimagic Susceptibility','The sword is incapacitated while in the area of an antimagic field. If targeted by dispel magic, the sword must succeed on a Constitution saving throw against the caster''s spell save DC or fall unconscious for 1 minute.'], ['False Appearance','While the sword remains motionless and isn''t flying, it is indistinguishable from a normal sword.'], ['Constructed Nature','An animated object doesn''t require air, food, drink, or sleep']],
  ARRAY[['Longsword','Melee Weapon Attack: +3 to hit, reach 5ft., one target. Hit: (1d8 + 1) slashing damage.']]),

  ('Rug of Smothering',
  'Large construct, unaligned',
  '12',
  '6d10',
  10,
  null,
  null,
  null,
  null,
  17,
  3,
  14,
  2,
  10,
  0,
  1,
  -5,
  3,
  -4,
  1,
  -5,
  null,
  null,
  null,
  null,
  'poison, psychic, blinded, charmed, deafened, frightened, paralyzed, petrified, poisoned',
  'Blindsight 60 ft. (blind beyond this radius)',
  'None',
  2,
  450,
  ARRAY[['Antimagic Susceptibility','The sword is incapacitated while in the area of an antimagic field. If targeted by dispel magic, the sword must succeed on a Constitution saving throw against the caster''s spell save DC or fall unconscious for 1 minute.'], ['Damage Transfer','While it is grappling a creature, the rug takes only half the damage dealt to it, and the creature grappled by the rug takes the other half.'], ['False Appearance','While the sword remains motionless and isn''t flying, it is indistinguishable from a normal sword.'], ['Constructed Nature','An animated object doesn''t require air, food, drink, or sleep']],
  ARRAY[['Smother','Melee Weapon Attack: +5 to hit, reach 5 ft., one Medium or smaller creature. Hit: The creature is grappled (escape DC 13). Until this grapple ends, the target is restrained, blinded, and at risk of suffocating, and the rug can''t smother another target. In addition, at the start of each of the target''s turns, the target takes (2d6 + 3) bludgeoning damage.']]),

  ('Ankheg',
  'Large monstrosity, unaligned',
  '14 (natural armor), 11 while prone',
  '6d10 + 6',
  30,
  10,
  null,
  null,
  null,
  17,
  3,
  11,
  0,
  13,
  1,
  1,
  -5,
  13,
  1,
  6,
  2,
  null,
  null,
  null,
  null,
  null,
  'Darkvision 60 ft., tremorsense 60 ft., passive Perception 11',
  'None',
  2,
  450,
  null,
  ARRAY[['Bite','Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: (2d6 + 3) slashing damage plus (1d6) acid damage. If the target is a Large or smaller creature, it is grappled (escape DC 13). Until this grapple ends, the ankheg can bite only the grappled creature and has advantage on attack rolls to do so.'], ['Acid Spray (Recharge 6)','The ankheg spits acid in a line that is 30 feet long and 5 feet wide, provided taht it has no creature grappled. Each creature in that line must make a DC 13 Dexterity saving throw, taking (3d6) acid damage on a failed save, or half as much damage on a successful one.']]),

  ('Azer',
  'Medium elemental, lawful neutral',
  '17 (natural armor, shield)',
  '6d8 + 12',
  30,
  null,
  null,
  null,
  null,
  17,
  3,
  12,
  1,
  15,
  2,
  12,
  1,
  13,
  1,
  10,
  0,
  'Con +4',
  null,
  null,
  null,
  'fire, poison, poisoned',
  'passive Perception 11',
  'Ignan',
  2,
  450,
  ARRAY[['Heated Body','A creature that touches the azer or hits it with a melee attack while within 5 feet of it takes (1d10) fire damage.'], ['Heated Weapons','When the azer hits with a metal melee weapon, it deals an extra (1d6) fire damage (included in the attack).'], ['Illumination','The azer sheds bright light in a 10-foot radius and dim light for an additional 10 feet.'], ['Living Fire','An azer doesn''t require food, drink, or sleep.']],
  ARRAY[['Warhammer','Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: (1d8 + 3) bludgeoning damage, or (1d10 + 3) bludgeoning damage if used with two hands to make a melee attack, plus (1d6) fire damage.']]);

INSERT INTO users (username, fullname, password, nickname)
VALUES 
  ('usera','Aaron Aaronson','$2a$12$IpHCvJOhVSyuK9I020hekOsuPi95/ReFe3MGUlzHUMIHP.pS4NQvy','AA'),
  ('userb','Betty Baxter','$2a$12$2WHnQO6/Tt2H4pji.KR7zu3XpD4oBoUo.lepQiK0vuFEiLRilL2Zu','BB'),
  ('userc','Charlie Chaplan','$2a$12$t/bGanhT0dU2xBg5GM.7dOWGi/r0hrjV1pBCbkU6rpUpajPEcnE.K','CC'),
  ('userd','Deborah Dirk','$2a$12$YOkClsAiStXU6VG.H6kEi.JoByEo9hp47ml0wDAdbnSAksPsz9WIa','DD'),
  ('usere','Eustace Evergreen','$2a$12$CK4Z.24buYLktMgwDkZE2.Gdva.hg/5B3r8lxTJ1CcwQNcvQBwOCe','EE');

INSERT INTO campaigns (title,campaignuserid)
VALUES
  ('Azeroth',1),('Blest',2),('Camelot',3),('Discworld',4),('Essos',5),('Fillory',1),('Grishaverse',1),('Halla',2),('Idris',3);

INSERT INTO encounters (encountername,encounterdesc,encountercampaignid)
VALUES
  ('Arbory','Bandit gang',1),('Bank','Angry bank tellers',2),('Castle Grounds','Castle Guards',3),('Dark Cave','Goblins',4),('Eagle''s Nest','Flock of Seagulls',5),('Foyer','Assassin Butler',6),('Green Fields','Wolves',7),('Highland Forest','Pixie Swarm',8),('Island Retreat','Merfolk Natives',9),('Jester''s College','Prakster Pugilists',1),('Karaoke Bar','Rocking Rabble',1),('Limestone Caverns','Ant Warriors',2);

INSERT INTO characters (npc,pcclass,level,pcname,initiative,ac,hp,hpmax,pcencounterid,pccampaignid,pcbestiaryid)
VALUES
  (FALSE,'Monk',3,'pa1',null,15,23,29,null,1,null),
  (FALSE,'Paladin',3,'pb1',null,18,32,32,null,1,null),
  (FALSE,'Wizard',3,'pc1',null,12,15,20,null,1,null),
  (FALSE,'Monk',3,'pa2',null,15,23,29,null,2,null),
  (FALSE,'Paladin',3,'pb2',null,18,32,32,null,2,null),
  (FALSE,'Wizard',3,'pc2',null,12,15,20,null,2,null),
  (FALSE,'Monk',3,'pa3',null,15,23,29,null,3,null),
  (FALSE,'Paladin',3,'pb3',null,18,32,32,null,3,null),
  (FALSE,'Wizard',3,'pc3',null,12,15,20,null,3,null),
  (FALSE,'Monk',3,'pa4',null,15,23,29,null,4,null),
  (FALSE,'Paladin',3,'pb4',null,18,32,32,null,4,null),
  (FALSE,'Wizard',3,'pc4',null,12,15,20,null,4,null),
  (FALSE,'Monk',3,'pa5',null,15,23,29,null,5,null),
  (FALSE,'Paladin',3,'pb5',null,18,32,32,null,5,null),
  (FALSE,'Wizard',3,'pc5',null,12,15,20,null,5,null),
  (TRUE,null,null,'Aarakocra1',5,12,24,24,1,null,1),
  (TRUE,null,null,'Aarakocra3',15,12,20,20,3,null,1),
  (TRUE,null,null,'Aboleth2',5,17,88,126,2,null,2),
  (TRUE,null,null,'Aboleth4',15,17,75,115,4,null,2),
  (TRUE,null,null,'Deva5',5,17,64,100,5,null,3),
  (TRUE,null,null,'Deva6',15,17,20,85,6,null,3),
  (TRUE,null,null,'Planetar5',5,19,24,24,5,null,4),
  (TRUE,null,null,'Planetar6',15,19,20,20,6,null,4),
  (TRUE,null,null,'Solar5',5,19,24,24,5,null,5),
  (TRUE,null,null,'Solar6',15,19,20,20,6,null,5);

COMMIT