BEGIN;

TRUNCATE 
bestiary
RESTART IDENTITY CASCADE;

INSERT INTO bestiary
  (monstername,type,ac,maxhp,speed,burrowspeed,climbspeed,flyspeed,swimspeed,str,strmod,dex,dexmod,con,conmod,int,intmod,wis,wismod,cha,chamod,savingthrows,skills,vulnerabilities,resistances,immunities,senses,languages,cr,xp,extras,actions)
VALUES
  ('Aarakocra',
  'Medium humanoid, neutral good',
  12,
  '3d8',
  20,
  null,
  null,
  50,
  null,
  10,
  0,
  14,
  2,
  10,
  0,
  11,
  0,
  12,
  1,
  11,
  0,
  null,
  'Perception +5',
  null,
  null,
  null,
  'passive Perception 15',
  'Auran',
  0.25,
  50,
  ARRAY[['Dive Attack', 'If the aarakocra if flying and dives at least 30 ft straight toward a target and then hits it with a melee weapon attack, the attack deals an extra (1d6) damage to the target.']],
  ARRAY[['Talon','Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit:(1d4+2) slashing damage']]),

  ('Aboleth',
  'Large aberration, lawful evil',
  '17 (natural armor)',
  '18d10 + 36',
  10,
  null,
  null,
  null,
  40,
  21,
  5,
  9,
  -1,
  15,
  2,
  18,
  4,
  15,
  2,
  18,
  4,
  'Con +6, Int +8, Wis +6',
  'History +12, Perception +10',
  null,
  null,
  null,
  'Darkvision 120ft, passive Perception 20',
  'Deep Speech, telepathy 120 ft.',
  10,
  5900,
  ARRAY[['Amphibious','The aboleth can breathe air and water'], ['Mucous Cloud','While underwater, the aboleth is surrounded by ransformative mucus. A creature that touches the aboleth or that hits it with a melee attack while within 5 feet of it must make a DC 14 Constitution saving throw. On a failure, the creature is deseased for (1d4) hours. The diseased creature can breath only underwater'], ['Probing Telepathy','If a creature communicates telepathically with the aboleth, the aboleth learns the creature''s greatest desires if the aboleth can see the creature.']],
  ARRAY[['Multiattack','The aboleth makes three tentacle attacks.'], ['Tentacle','Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: (2d6+5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased. The disease has no effect for 1 minute and can be removed by any magic that cures disease. After 1 minute, the diseased creature''s skin becomes translucent and slimy, the creature can''t regain hit points unless it is underwater, and the disease can be removed only by heal or another disease-curing spell of 6th level or higher. When the creature is outside a body of water, it takes (1d12) acid damage every 10 minutes unless moisture is applied to the skin before 10 minutes have passed.'], ['Tail','Melee Weapon Attack: +9 to hit, reach 10 ft. one target. Hit: (3d6 + 5) bludgeoning damage.'], ['Enslave (3/Day)','The aboleth targets one creature it can see within 3 feet of it. The target must succeed on a DC 14 Wisdom saving throw or be magically charmed by the aboleth until the abolthe dies or until it is on a different plane of existence from the target. The charmed target is under the aboleth''s control and can''t take reactions, and the aboleth and the target can communicate telepathically with each other over any distance'], ['Legendary Actions','The aboleth can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature''s turn. The aboleth regains spent legendary actions at the start of its turn.   Detect: The aboleth makes a Wisdom (Perception) check.   Tail Swipe: The aboleth makes one tail attack.   Psychic Drain (Costs 2 Actions): One creature charmed by the aboleth takes (3d6) psychic damage, and the aboleth regains hit points equal to the damage the creature takes.']]),

  ('Angel: Deva',
  'Medium celestial, lawful good',
  '17 (natural armor)',
  '16d8 + 64',
  30,
  null,
  null,
  90,
  null,
  18,
  4,
  18,
  4,
  18,
  4,
  17,
  3,
  20,
  5,
  20,
  5,
  'Wis +9, Cha +9',
  'Insight +7, Perception +9',
  null,
  'radiant; bludgeoning, piercing, and slashing from nonmagical weapons',
  'charmed, exhaustion, frightened',
  'darkvision 120 ft., passive Perception 19',
  'all, telepathy 120 ft',
  10,
  5900,
  ARRAY[['Angelic Weapons','The deva''s weapon attacks are magical. When the deva hits with any weapon, the weapon deals an extra (4d8) radiant damage (included in the attack)'], ['Innate Spellcasting','The deva''s spellcasting ability is Charisma (spell save DC 17). The deva can innately cast the following spells, requiring only verbal components:   At will: detect evil and good,   1/day: commune, raise dead'], ['Magic Resistance','The deva has advantage on saving throws against spells and other magical effects.']],
  ARRAY[['Multiattack', 'The deva makes two melee attacks.'], ['Mace', 'Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: (1d6 + 4) bludgeoning damage plus (4d8) radiant damage.'], ['Healing Touch (3/Day)', 'The deva touches another creature. The target magically regains (4d8 + 2) hit points and is freed from any curse, disease, poison, blindness, or deafness.'], ['Change Shape', 'The deva magically polymorphs into a humanoid or beast that has a challenge rating equal to or less than its own, or back into its true form. It reverts to its true form if it dies. Any equipment it is wearing or carrying is absorbed or borne by the new form (the deva''s choice). In a new form, the deva retains its game statistics and ability to speak, but its AC, movement modes, Strength, Dexterity, and special senses are replaced by those of the new form, and it gains any statistics and capabilities (except class features, legendary actions, and lair actions) that the new form has but that it lacks.']]),

  ('Angel: Planetar',
  'Large celestial, lawful good',
  '19 (natural armor)',
  '16d10 + 112',
  40,
  null,
  null,
  120,
  null,
  24,
  7,
  20,
  5,
  24,
  7,
  19,
  4,
  22,
  6,
  25,
  7,
  'Con +12, Wis +11, Cha+12',
  'Perception +11',
  null,
  'radiant; bludgeoning, piercing, and slashing from non-magical weapons',
  'charmed, exhaustion, frightened',
  'Truesight 120 ft., passive Perception 21',
  'all, telepathy 120 ft.',
  16,
  15000,
  ARRAY[['Angelic Weapons','The planetar''s weapon attacks are magical. When the planetar hits with any weapon, the weapon deals an extra (5d8) radiant damage (included in the attack).'], ['Divine Awareness','The planetar knows if it hears a lie'], ['Innate Spellcasting','The planetar''s spellcasting ability is Charisma (spell save DC 20). The planetar can innately cast the following spells, requiring no material components:   At will: detect evil and good, invisibility (self only)   3/day each: blade barrier, dispel evil and good, flame strike, raise dead   1/day each: commune, control weather, insect plague'], ['Magic Resistance','The planetar has advantage on saving throws against spells and other magical effects.']],
  ARRAY[['Multiattack','The planetar makes two melee attacks'], ['Greatsword','Melee Weapon Attack: +12 to hit, reach 5 ft., one target. Hit: (4d6 + 7) slashing damage plus (5d8) radiant damage'], ['Healing Touch (4/Day)','The planetar touches another creature. The target magically regains (6d8 + 3) hit points and is freed from any curse, disease, poison, blindness, or deafness']]),

  ('Angel: Solar',
  'Large celestial, lawful good',
  '21 (natural armor)',
  '18d10 + 144',
  50,
  null,
  null,
  150,
  null,
  26,
  8,
  22,
  6,
  26,
  8,
  25,
  7,
  25,
  7,
  30,
  10,
  'Int +14, Wis +14, Cha +17',
  'Perception +14',
  null,
  'radiant; bludgeoning, piercing, and slashing from nonmagical weapons',
  'necrotic, poison, charmed, exhaustion, frightened, poisoned',
  'Truesight 120 ft., passive Perception 24',
  'all, telepathy 120 ft.',
  21,
  33000,
  ARRAY[['Angelic Weapons','The solar''s weapon attacks are magical. When the solar hits with any weapon, the weapon deals an extra (6d8) radiant damage (included in the attack).'], ['Divine Awareness','The planetar knows if it hears a lie'], ['Innate Spellcasting','The solar''s spellcasting ability is Charisma (spell save DC 25). It can innately cast the following spells, requiring no material components:   At will: detect evil and good, invisibility (self only)   3/day each: blade barrier, dispel evil and good, resurrection   1/day each: commune, control weather'], ['Magic Resistance','The solar has advantage on saving throws against spells and other magical effects.']],
  ARRAY[['Multiattack','The solar makes two greatsword attacks'], ['Greatsword','Melee Weapon Attack: +15 to hit, reach 5 ft., one target. Hit: (4d6 + 8) slashing damage plus (6d8) radiant damage'], ['Slaying Longbow','Ranged Weapon Attack: +13 to hit, range 120/600 ft., one target. Hit: (2d8 + 6) piercing damage plus (6d8) radiant damage. If the target is a creature that has 100 hit points or fewer, it must succeed on a DC 15 Constitution saving throw or die'], ['Flying Sword','The solar releases its greatsword to hover magically in an unoccupied space within 5 feet of it. if the solar can see the sword, the solar can mentally command it as a bonus action to fly up to 50 feet and either make one attack against a target or return to the solar''s hands. If the hovering sword is targeted by any effect, the solar is considered to be holding it. The hovering sword falls if the solar dies.'], ['Healing Touch (4/Day)','The solar touches another creature. The target magically regains (8d8 + 4) hit points and is freed from any curse, disease, poison, blindness, or deafness'], ['Legendary Actions','The solar can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature''s turn. The solar regains spent legendary actions at the start of its turn.   Teleport: The solar magically teleports, along with any equipment it is wearing or carrying, up to 120 feet to an unoccupied space it can see.   Searing Burst (Costs 2 Actions): The solar emits magical, divine energy. Each creature of its choice in a 10 -foot radius must make a DC 23 Dexterity saving throw, taking (4d6) fire damage plus (4d6) radiant damage on a fai led save, or half as much damage on a successful one.   Blinding Gaze (Costs 3 Actions): The solar targets one creature it can see within 30 feet of it. If the target can see it, the target must succeed on a DC 15 Constitution saving throw or be blinded until magic such as the lesser restoration spell removes the blindness.']]),

  ('Animated Armor',
  'Medium construct, unaligned',
  '18 (natural armor)',
  '6d8 + 6',
  25,
  null,
  null,
  null,
  null,
  14,
  2,
  11,
  0,
  13,
  1,
  1,
  -5,
  3,
  -4,
  1,
  -5,
  null,
  null,
  null,
  null,
  'poison, psychic, blinded, charmed deafened, exhaustion, frightened, paralyzed, petrified, poisoned',
  'Blindsight 60 ft. (blind beyond this radius), passive Perception 6',
  'None',
  1,
  200,
  ARRAY[['Antimagic Susceptibility','The armor is incapacitated while in the area of an antimagic field. If targeted by dispel magic, the armor must succeed on a Constitution saving throw against the caster''s spell save DC or fall unconscious for 1 minute.'], ['False Appearance','While the armor remains motionless, it is indistinguishable from a normal suit of armor'], ['Constructed Nature','An animated object doesn''t require air, food, drink, or sleep']],
  ARRAY[['Multiattack','The armor makes two melee attacks'], ['Slam','Melee Weapon Attack: +4 to hit, reach 5ft., one target. Hit (1d6 + 2) bludgeoning damage']]),
  
  ('Flying Sword',
  'Small construct, unaligned',
  '17 (natural armor)',
  '5d6',
  0,
  null,
  null,
  50,
  null,
  12,
  1,
  15,
  2,
  11,
  0,
  1,
  -5,
  5,
  -3,
  1,
  -5,
  'Dex +4',
  null,
  null,
  null,
  'poison, psychic, blinded, charmed, deafened, frightened, paralyzed, petrified, poisoned',
  'Blindsight 60 ft. (blind beyond this radius)',
  'None',
  0.25,
  50,
  ARRAY[['Antimagic Susceptibility','The sword is incapacitated while in the area of an antimagic field. If targeted by dispel magic, the sword must succeed on a Constitution saving throw against the caster''s spell save DC or fall unconscious for 1 minute.'], ['False Appearance','While the sword remains motionless and isn''t flying, it is indistinguishable from a normal sword.'], ['Constructed Nature','An animated object doesn''t require air, food, drink, or sleep']],
  ARRAY[['Longsword','Melee Weapon Attack: +3 to hit, reach 5ft., one target. Hit: (1d8 + 1) slashing damage.']]),

  ('Rug of Smothering',
  'Large construct, unaligned',
  '12',
  '6d10',
  10,
  null,
  null,
  null,
  null,
  17,
  3,
  14,
  2,
  10,
  0,
  1,
  -5,
  3,
  -4,
  1,
  -5,
  null,
  null,
  null,
  null,
  'poison, psychic, blinded, charmed, deafened, frightened, paralyzed, petrified, poisoned',
  'Blindsight 60 ft. (blind beyond this radius)',
  'None',
  2,
  450,
  ARRAY[['Antimagic Susceptibility','The sword is incapacitated while in the area of an antimagic field. If targeted by dispel magic, the sword must succeed on a Constitution saving throw against the caster''s spell save DC or fall unconscious for 1 minute.'], ['Damage Transfer','While it is grappling a creature, the rug takes only half the damage dealt to it, and the creature grappled by the rug takes the other half.'], ['False Appearance','While the sword remains motionless and isn''t flying, it is indistinguishable from a normal sword.'], ['Constructed Nature','An animated object doesn''t require air, food, drink, or sleep']],
  ARRAY[['Smother','Melee Weapon Attack: +5 to hit, reach 5 ft., one Medium or smaller creature. Hit: The creature is grappled (escape DC 13). Until this grapple ends, the target is restrained, blinded, and at risk of suffocating, and the rug can''t smother another target. In addition, at the start of each of the target''s turns, the target takes (2d6 + 3) bludgeoning damage.']]),

  ('Ankheg',
  'Large monstrosity, unaligned',
  '14 (natural armor), 11 while prone',
  '6d10 + 6',
  30,
  10,
  null,
  null,
  null,
  17,
  3,
  11,
  0,
  13,
  1,
  1,
  -5,
  13,
  1,
  6,
  2,
  null,
  null,
  null,
  null,
  null,
  'Darkvision 60 ft., tremorsense 60 ft., passive Perception 11',
  'None',
  2,
  450,
  null,
  ARRAY[['Bite','Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: (2d6 + 3) slashing damage plus (1d6) acid damage. If the target is a Large or smaller creature, it is grappled (escape DC 13). Until this grapple ends, the ankheg can bite only the grappled creature and has advantage on attack rolls to do so.'], ['Acid Spray (Recharge 6)','The ankheg spits acid in a line that is 30 feet long and 5 feet wide, provided taht it has no creature grappled. Each creature in that line must make a DC 13 Dexterity saving throw, taking (3d6) acid damage on a failed save, or half as much damage on a successful one.']]),

  ('Azer',
  'Medium elemental, lawful neutral',
  '17 (natural armor, shield)',
  '6d8 + 12',
  30,
  null,
  null,
  null,
  null,
  17,
  3,
  12,
  1,
  15,
  2,
  12,
  1,
  13,
  1,
  10,
  0,
  'Con +4',
  null,
  null,
  null,
  'fire, poison, poisoned',
  'passive Perception 11',
  'Ignan',
  2,
  450,
  ARRAY[['Heated Body','A creature that touches the azer or hits it with a melee attack while within 5 feet of it takes (1d10) fire damage.'], ['Heated Weapons','When the azer hits with a metal melee weapon, it deals an extra (1d6) fire damage (included in the attack).'], ['Illumination','The azer sheds bright light in a 10-foot radius and dim light for an additional 10 feet.'], ['Living Fire','An azer doesn''t require food, drink, or sleep.']],
  ARRAY[['Warhammer','Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: (1d8 + 3) bludgeoning damage, or (1d10 + 3) bludgeoning damage if used with two hands to make a melee attack, plus (1d6) fire damage.']]),
  
  ('Banshee',
  'Medium undead, chaotic evil',
  '12',
  '13d8',
  0, null, null, 40, null,
  1, -5, 14, 2, 10, 0, 12, 1, 11, 0, 17, 3,
  'Wis +2, Cha +4',
  null,
  null,
  'acid, fire, lightning, thunder; bludgeoning, piercing, and slashing from nonmagical weapons',
  'cold, necrotic, poison; charmed, exhaustion, frightened, grappled, paralyzed, petrified, poisoned, prone, restrained',
  'Darkvision 60ft, passive Perception 10',
  'Common, Elvish',
  4,
  1100,
  ARRAY[['Hover','The banshee hovers above the ground for purposes of movement and does not actually fly'],['Detect Life','The banshee can magically sense the presence of living creatures up to 5 miles away. She knows the general direction they''re in but not their exact locations.'],['Incorporeal Movement','The banshee can move through other creatures and objects as if they were difficult terrain. She takes 5 (1d10) force damage if she ends her turn inside an object']],
  ARRAY[['Corrupting Touch','Melee Spell Attack: +4 to hit, reach 5ft, one target. Hit: 12 (3d6 + 2) necrotic damage.'],['Horrifying Visage','Each non-undead creature within 60 feet of the banshee that can see her must succeed on a DC 13 Wisdom saving throw or be frightened for 1 minute. A frightened target can repeat the saving throw at the end of each of its turns, with disadvantage if the banshee is within line of sight, ending the effect on itself on a success. If a ta rget''s saving throw is successful or the effect ends for it, the target is immune to the banshee''s Horrifying Visage for the next 24 hours.'],['Wail (1/Day)','The banshee releases a mournful wail, provided that she isn''t in sunlight. This wail has no effect on constructs and undead. All other creatures within 30 ft of her that can hear her must make a DC 13 Con saving throw. On a failure, a creature drops to 0 hit points. On a success, a creature takes 10 (3d6) psychic damage.']]
  ),
  
  ('Basilisk',
  'Medium monstrosity, unaligned',
  '15 (natural armor)',
  '858 + 16',
  20, null, null, null, null,
  16, 3, 8, -1, 15, 2, 2, -4, 8, -1, 7, -2,
  null,
  null,
  null,
  null,
  null,
  'Darkvision 60ft, passive Perception 9',
  null,
  3,
  700,
  ARRAY[['Petrifying Gaze',E'If a creature starts its turn within 30 feet of the basilisk and the two of them can see each other, the basilisk can force the creature to make a DC 12 Constitution saving throw if the basilisk isn''t incapacitated. On a failed save, the creature magically begins to turn to stone and is restrained. It must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure , the creature is petrified until freed by the greater restoration spell or other magic. \n  A creature that isn''t surprised can avert its eyes to avoid the saving throw at the start of its turn. If it does so, it can''t see the basilisk until the start of its next turn, when it can avert its eyes again. If it looks at the basilisk in the meantime, it must immediately make the save. \n  If the basilisk sees its reflection within 30 feet of it in bright light, it mistakes itself for a rival and targets itself with its gaze.']],
  ARRAY[['Bite','Melee Weapon Attack: +5 to hit, reach 5 ft, one target. Hit: (2d6 + 3) piercing damage plus (2d6) poison damage']]),
  
  ('Behir',
  'Huge monstrosity, neutral evil',
  '17 (natural armor)',
  '16d12 + 64',
  50, null, 40, null, null,
  23,6,16,3,18,4,7,-2,14,2,12,1,
  null,
  'Perception +6, Stealth +7',
  null,
  null,
  'lightning',
  'Darkvision 90ft, passive Perception 16',
  'Draconic',
  11,7200,
  null,
  ARRAY[['Multiattack','The behir makes two attacks: one with its bite and one to constrict'],['Bite','Melee Weapon Attack: +10 to hit, reach 10 ft, one target. Hit: (3d10 + 6) piercing damage'],['Constrict', 'Melee Weapon Attack: + 10 to hit, reach 5 ft, one Large or smaller creature. Hit: 17 (2d10 + 6) bludgeoning damage plus (2d10 + 6) slashing damage. The target is grappled (escape DC 16) if the behir isn''t already constricting a creature, and the target is restrained until this grapple ends.'],['Lightning Breath (Recharge 5-6)', 'The behir exhales a line of lightning that is 20 feet long and 5 feet wide. Each creature in that line must make a DC 16 Dexterity saving throw, taking (12d10) lightning damage on a failed save, or half as much damage on a successful one.'],['Swallow', E'The behir makes one bite attack against a Medium or smaller target it is grappling. If the attack hits, the target is also swallowed, and the grapple ends. While swallowed, the target is blind ed and restrained, it has total cover against attacks and other effects outside the behir, and it takes (6d6) acid damage at the start of each of the behir''s turns. A behir can have only one creature swallowed at a time. \n  If the behir takes 30 damage or more on a single turn from the swallowed creature, the behir must succeed on a DC 14 Constitution saving throw at the end of that turn or regurgitate the creature, which falls prone in a space within 10 feet of the behir. If the behir dies, a swallowed creature is no longer restrained by it and can escape from the corpse by using 15 feet of movement, exiting prone.']]
  ),
  
  ('Beholder',
  'Large aberration, lawful evil',
  '18 (natural armor)',
  '19d10 + 76',
  0,null,null,20,null,
  10,0,14,2,18,4,17,3,15,2,17,3,
  'Int +8, Wis +7, Cha +8',
  'Perception +12',
  null,
  null,
  'prone',
  'Darkvision 120 ft, passive Perception 22',
  'Deep Speech, Undercommon',
  13,10000,
  ARRAY[['Hover','The beholder hovers above the ground for purposes of movement and does not actually fly'],['Antimagic Cone','The beholder''s central eye creates an area of antimagic, as in the antimagic field spell, in a 150-foot cone. At the start of each of its turns, the beholder decides which way the cone faces and whether the cone is active. The area works against the beholder''s own eye rays.'],['Lair Actions',E'When fighting insides its lair, a beholder can invoke the ambient magic to take lair actions. On initiative count 20 (losing initiative ties), the beholder can take one lair action to cause one of the following effects: \n  A 50-foot square area of ground within 120 ft of the beholder becomes slimy; that area is difficult terrain until initiative count 20 on the next round. \n  Walls within 120 ft of the beholder sprout grasping appendages until initiative count 20 on the round after next. Each creature of the beholder''s choice that starts its turn within 10 ft of such a wall must succeed on a DC 15 Dex saving throw or be grappled. Escaping requires a successful DC 15 Str (Athletics) or Dex (Acrobatics) check. \n  An eye opens on a solid surface within 60 ft of the beholder. One random eye ray of the beholder shoots form that eye at a target of the beholder''s choice that it can see. The eye then closes and disappears.\n\nThe beholder can''t repeat an effect until they have all been used, and it can''t sue the same effect two rounds in a row.'],['Regional Effects',E'A region containing a beholder''s lair is warped by the creature''s unnatural presence, which creates one of more of the following effects:\n  Creatures within 1 mile of the beholder''s lair some-times feel as if they''re being watched when they aren''t.\n  When the beholder sleeps, minor warps in reality occur within 1 mile of its lair and then vanish 24 hours later. Marks on cave walls might change subtly, an eerie trinket might appear where none existed before, harmless slime might coat a statue, and so on. These effects apply only to natural surfaces and to nonmagical objects that aren''t on anyone''s person.\n\nIf the beholder dies, these effects fade over the course of 1d10 days.']],
  ARRAY[['Bite','Melee Weapon Attack: +5 to hit, reach 5ft, one target. Hit: (4d6) piercing damage.'],['Eye Rays',E'The beholder shoots three of the following magical eye rays at random (reroll duplicates), choosing one to three targets it can see within 120 feet of it:\n 1. Charm Ray: The targeted creature must succeed on a DC 16 Wis saving throw or be charmed by the beholder for 1 hour, or until the beholder harms the creature.\n 2. Paralyzing Ray: the targeted creature must succeed on a DC 16 Con saving throw or be paralyzed for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.\n 3. Fear Ray: The targeted creature must succeed on a DC 16 Wis saving throw or be frightened for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.\n 4. Slowing Ray: The targeted creature must succeed on a DC 16 Dex saving throw. On a failed save, the target''s speed is halved for 1 minute. In addition, the creature can''t take reactions, and it can take either an action or a bonus action on its turn, not both. The creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.\n 5. Enervation Ray: The targeted creature must make a DC 16 Con saving throw, taking (8d8) necrotic damage on a failed save, or half as much damage on a successful one.\n 6. Telekinetic Ray: If the target is a creature, it must succeed on a DC 16 Str saving throw or the beholder moves it up to 30 feet in any direction. It is restrained by the ray''s telekinetic grip until the start of the beholder''s next turn or until the beholder is incapacitated. If the target is an object weighing 300 pounds or less that isn''t being worn or carried, it is moved up to 30 feet in any direction. The beholder can also exert fine control on objects with this ray, such as manipulating a simple tool or opening a door or a container.\n 7. Sleep Ray: The targeted creature must succeed on a DC 16 Wis saving throw or fall asleep and remain unconscious for 1 minute. The target awakens if it takes damage or another creature takes an action to wake it. This ray has no effect on constructs and undead.\n 8. Petrification Ray: The targeted creature must make a DC 16 Dex saving throw. On a failed save, the creature begins to turn to stone and is restrained. It must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure, the creature is petrified until freed by the greater restoration spell or other magic.\n 9. Disintegration Ray: If the target is a creature, it must succeed on a DC 16 Dex saving throw or take (10d8) force damage. If this damage reduces the creature to 0 hit points, its body becomes a pile of fine gray dust. If the target is a Large or smaller non magical object or creation of magical force, it is disintegrated without a saving throw. If the target is a Huge or larger object or creation of magical force, this ray disintegrates a 10-foot cube of it.\n 10. Death Ray: The targeted creature must succeed on a DC 16 Dex saving throw or take (10d10) necrotic damage. The target dies if the ray reduces it to 0 hit points.'],['Legendary Actions','The beholder can take 3 legendary actions, each using one random eye ray. It can take only one legendary action at a time and only at the end of another creature''s turn. The beholder regains spent legendary actions at the start of its turn.']]),
  
  ('Beholder: Death Tyrant','Large undead, lawful evil',
  '19 (natural armor)', '25d10 + 50',
  0,null,null,20,null,
  10,0,14,2,14,2,19,4,15,2,19,4,
  'Str +5, Con +7, Int +9, Wis +7, Cha +9',
  'Perception +12',null,null,'poison; charmed, exhaustion, paralyzed, petrified, poisoned, prone',
  'Darkvision 120 ft, passive Perception 22',
  'Deep Speech, Undercommon',
  4,11500,
  ARRAY[['Hover','The beholder hovers above the ground for purposes of movement and does not actually fly'],['Negative Energy Cone',E'The death tyrant''s eye emits an invisible, magical 150-foot cone of negative energy. At the start of each of its turns, the tyrant decides which way the cone faces and whether the cone is active.\n  Any creature in that area can''t regain hit points. Any humanoid that dies there becomes a zombie under the tyrant''s command. the dead humanoid retains its place in the initiative order and animates at the start of its next turn, provided that its body hasn''t been completely destroyed.'],['Lair Actions','When fighting inside its lair, a death tyrant can invoke the ambient magic to take lair actions. On initiative count 20 (losing initiative ties), the death tyrant can take one lair action to cause one of the following effects:\n  An area that is a 50-foot cube within 120 feet of the tyrant is filled with spectral eyes and tentacles. To creatures other than the death tyrant, that area is lightly obscured and difficult terrain until initiative count 20 on the next round.\n  Walls sprout spectral appendages until initiative count 20 on the round after next. Any creature, including one on the Ethereal Plane, that is hostile to the tyrant and starts its turn within 10 feet of a wall must succeed on a DC 17 Dexterity saving throw or be grappled. Escaping requires a successful DC 17 Strength (Athletics) or Dexterity (Acrobatics) check.\n  A spectral eye opens in the air at a point within 50 feet of the tyrant. One random eye ray of the tyrant shoots from that eye, which is considered to be an ethereal source, at a target of the tyrant''s choice. The eye then closes and disappears. The death tyrant can''t repeat an effect until all three have been used, and it can''t use the same effect on consecutive rounds.'],['Regional Effects','A region containing a death tyrant''s lair is warped by the creature''s unnatural presence, which creates one or more of the following effects:\n  Creatures within 1 mile of the tyrant''s lair sometimes feel as if they''re being watched even when they aren''t. When a creature hostile to the tyrant and aware of its existence finishes a long rest within 1 mile of the tyrant''s lair, roll a d20 for that creature. On a roll of 10 or lower, the creature is subjected to one random eye ray of the tyrant.\nIf the death tyrant dies, these effects fade over the course of 1d10 days.']],
  ARRAY[['Bite','Melee Weapon Attack: +5 to hit, reach 5ft, one target. Hit: (4d6) piercing damage.'],['Eye Rays',E'The beholder shoots three of the following magical eye rays at random (reroll duplicates), choosing one to three targets it can see within 120 feet of it:\n 1. Charm Ray: The targeted creature must succeed on a DC 17 Wis saving throw or be charmed by the beholder for 1 hour, or until the beholder harms the creature.\n 2. Paralyzing Ray: the targeted creature must succeed on a DC 17 Con saving throw or be paralyzed for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.\n 3. Fear Ray: The targeted creature must succeed on a DC 17 Wis saving throw or be frightened for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.\n 4. Slowing Ray: The targeted creature must succeed on a DC 17 Dex saving throw. On a failed save, the target''s speed is halved for 1 minute. In addition, the creature can''t take reactions, and it can take either an action or a bonus action on its turn, not both. The creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.\n 5. Enervation Ray: The targeted creature must make a DC 17 Con saving throw, taking (8d8) necrotic damage on a failed save, or half as much damage on a successful one.\n 6. Telekinetic Ray: If the target is a creature, it must succeed on a DC 17 Str saving throw or the beholder moves it up to 30 feet in any direction. It is restrained by the ray''s telekinetic grip until the start of the beholder''s next turn or until the beholder is incapacitated. If the target is an object weighing 300 pounds or less that isn''t being worn or carried, it is moved up to 30 feet in any direction. The beholder can also exert fine control on objects with this ray, such as manipulating a simple tool or opening a door or a container.\n 7. Sleep Ray: The targeted creature must succeed on a DC 17 Wis saving throw or fall asleep and remain unconscious for 1 minute. The target awakens if it takes damage or another creature takes an action to wake it. This ray has no effect on constructs and undead.\n 8. Petrification Ray: The targeted creature must make a DC 17 Dex saving throw. On a failed save, the creature begins to turn to stone and is restrained. It must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure, the creature is petrified until freed by the greater restoration spell or other magic.\n 9. Disintegration Ray: If the target is a creature, it must succeed on a DC 17 Dex saving throw or take (10d8) force damage. If this damage reduces the creature to 0 hit points, its body becomes a pile of fine gray dust. If the target is a Large or smaller non magical object or creation of magical force, it is disintegrated without a saving throw. If the target is a Huge or larger object or creation of magical force, this ray disintegrates a 10-foot cube of it.\n 10. Death Ray: The targeted creature must succeed on a DC 17 Dex saving throw or take (10d10) necrotic damage. The target dies if the ray reduces it to 0 hit points.'],['Legendary Actions','The beholder can take 3 legendary actions, each using one random eye ray. It can take only one legendary action at a time and only at the end of another creature''s turn. The beholder regains spent legendary actions at the start of its turn.']]),
  
  ('Beholder: Spectator','Medium aberration, lawful neutral',
  '14 (natural armor)','6d8 + 12',
  0,null,null,30,0,
  8,-1,14,2,14,2,13,1,14,2,11,0,
  null,'Perception +6',null,null,'prone',
  'Darkvision 120ft, passive Perception 16',
  'Deep Speech, Undercommon, telepathy 120ft',
  3,700,
  null,
  ARRAY[['Bite','Melee Weapon Attack: +1 to hit, reach 5ft, one target. Hit: (1d6 - 1) piercing damage'],['Eye Rays',E'The spectator shoots up to two of the following magical eye rays at one or two creatures it can see within 90 feet of it. It can use each ray only once on a turn.\n  1. Confusion Ray: The target must succeed on a DC 13 Wis saving throw, or it can''t take reactions until the end of its next turn. On its turn, the target can''t move, and it uses its action to make a melee or ranged attack against a randomly determined creature within range. If the target can''t attack, it does nothing on its turn.\n  2. Paralyzing Ray: The target must succeed on a DC 13 Con saving throw or be paralyzed for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect of itself on a success.\n  3. Fear Ray: The target must succeed on a DC 13 Wis saving throw or be frightened for 1 minute. The target can repeat the saving throw at the end of each of its turns, with disadvantage if the spectator is visible to the target, ending the effect on itself on a success.\n  4. Wounding Ray: The targeet must make a DC 13 Con saving throw, taking (3d10) necrotic damage on a failed save, or half as much damage on a successful one.'],['Create Food and Water','The spectator magically creates enough food and water to sustain itself for 24 hours.'],['Spell Reflection','Reaction: If the spectator makes a successful saving throw against a spell, or a spell attack misses it, the spectator can choose another creature (including the spellcaster) it can see within 30 feet of it. The spell targets the chosen creature instead of the spectator. If the spell forced a saving throw, the chosen creature makes its own save. If the spell was an attack, the attack roll is rerolled against the chosen creature.']]),
  
  ('Blight: Needle Blight','Medium plant, neutral evil',
  '12 (natural armor)','2d8 + 2',
  30,null,null,null,null,
  12,1,12,1,13,1,4,-3,8,-1,3,-4,
  null,null,null,null,'blinded, deafened',
  'Blindsight 60ft (blind beyond this radius), passive Perception 9',
  'understands Common, but cannot speak',0.25,50,
  null,
  ARRAY[['Claws','Melee Weapon Attack: +3 to hit, reach 5ft, one target. Hit: (2d4 + 1) piercing damage'],['Needles','Ranged Weapon Attack: +3 to hit, range 30/60ft, one target. Hit: (2d6 + 1) piercing damage.']]),
  
  ('Blight: Twig Blight','Small plant, neutral evil',
  '13 (natural armor)','1d6 + 1',
  20,null,null,null,null,
  6,-2,13,1,12,1,4,-3,8,-1,3,-4,
  null,'Stealth +3','fire',null,'blinded, deafened',
  'Blindsight 60ft (blind beyond this radius), passive Perception 9',
  'understands Common but cannot speak',0.125,25,
  ARRAY[['False Appearance','While the blight remains motionless, it is indistinguishable from a dead shrub.']],
  ARRAY[['Claws','Melee Weapon Attack: +3 to hit, reach 5ft, one target. Hit: (1d4 + 1) piercing damage.']]),
  
  ('Blight: Vine Blight','Medium plant, neutral evil',
  '12 (natural armor)','4d8 + 8',
  10,null,null,null,null,
  15,2,8,-1,14,2,5,-3,10,0,3,-4,
  null,'Stealth +1',null,null,'blinded, deafened',
  'Blindsight 60ft (blind beyond this radius), passive Perception 10',
  'Common',0.5,100,
  ARRAY[['False Appearance','While the blight remains motionless, it is indistinguishable from a dead shrub.']],
  ARRAY[['Constrict','Melee Weapon Attack: +4 to hit, reach 10ft, one target. Hit: (2d6 + 2) bludgeoning damage, and a Large or smaller target is grappled (escape DC 12). Until this grapple ends, the target is restrained, and the blight cannot constrict another target.'],['Entangling Plants (Recharge 5-6)','Grasping roots and vines sprout in a 15-foot radius centered on the blight, withering away after 1 minute. For the duration, that area is difficult terrain for non plant creatures. In addition, each creature of the blight''s choice in that area when the plants appear must succeed on a DC 12 Str saving throw or become restrained. A creature can use its action to make a DC 12 Str check, freeing itself or another entangled creature within reach on a success.']]),
  
  ('Bugbear','Medium humanoid (goblinoid), chaotic evil',
  '16 (hide armor, shield','5d8 + 5',
  30,null,null,null,null,
  15,2,14,2,13,1,8,-1,11,0,9,-1,
  null,'Stealth +6, Survival +2',null,null,null,
  'Darkvision 60ft, passive Perception 10',
  'Common, Goblin',1,200,
  ARRAY[['Brute','A melee weapon deals one extra die of its damage when the bugbear hits with it (included in the attack).'],['Surprise Attack','If the bugbear surprises a creature and hits it with an attack during the first round of combat, the target takes an extra (2d6) damage from the attack.']],
  ARRAY[['Morningstar','Melee Weapon Attack: +4 to hit, reach 5ft, one target. Hit: (2d8 + 2) piercing damage'],['Javelin','Melee or Ranged WEapon Attack: +4 to hit, reach 5ft, or range 30/120ft, one target. Hit: (2d6 + 2) piercing damage in melee or (1d6 + 2) piercing damage at range.']]),
  
  ('Bugbear Chief','Medium humanoid (goblinoid), chaotic evil',
  '17 (chain shirt, shield','10d8 + 20',
  30,null,null,null,null,
  17,3,14,2,14,2,11,0,12,1,11,0,
  null,'Intimidation +2, Stealth +6, Survival +3',null,null,null,
  'Darkvision 60ft, passive Perception 11',
  'Common, Goblin',3,700,
  ARRAY[['Brute','A melee weapon deals one extra die of its damage when the bugbear hits with it (included in the attack).'],['Heart of Hruggek','The bugbear has advantage on saving throws against being charmed, frightened, paralyzed, poisoned, stunned, or put to sleep.'],['Surprise Attack','If the bugbear surprises a creature and hits it with an attack during the first round of combat, the target takes an extra (2d6) damage from the attack.']],
  ARRAY[['Multiattack','The bugbear makes two melee attacks.'],['Morningstar','Melee Weapon Attack: +5 to hit, reach 5ft, one target. Hit: (2d8 + 3) piercing damage'],['Javelin','Melee or Ranged WEapon Attack: +4 to hit, reach 5ft, or range 30/120ft, one target. Hit: (2d6 + 3) piercing damage in melee or (1d6 + 3) piercing damage at range.']]),
  
  ('Bulette','Large monstrosity, unaligned','17 (natural armor)',
  '9d10 + 45',40,40,null,null,null,
  19,4,11,0,21,5,2,-4,10,0,5,-3,
  null,'Perception +6',null,null,null,
  'Darkvision 60ft, Tremorsense 60ft, passive Perception 16',
  null,5,1800,
  ARRAY[['Standing Leap','The bulette''s long jump is up to 30ft and its high jump is up to 15ft, with or without a running start']],
  ARRAY[['Bite','Melee Weapon Attack: +7 to hit, reach 5ft, one target. Hit: (4d12 + 4) piercing damage'],['Deadly Leap','If the bulette jumps at least 15 feet as part of its movement, it can then use this action to land on its feet in a space that contains one or more other creatures. Each of those creatures must succeed on a DC 16 Str or Dex saving throw (target''s choice) or be knocked prone and take (3d6 + 4) bludgeoning damage plus (3d6 + 4) slashing damage. On a successful save, the creature takes only half the damage , isn''t knocked prone, and is pushed 5 feet out of the bulette''s space into an unoccupied space of the creature''s choice. If no unoccupied space is with in range, the creature instead falls prone in the bulette''s space.']]),
  
  ('Bullywug','Medium humanoid (bullywug), neutral evil',
  '15 (hide armor, shield)','2d8 + 2',
  20,null,null,null,40,
  12,1,12,1,13,1,7,-2,10,0,7,-2,
  null,'Stealth +3',null,null,null,
  'passive Perception 10','Bullywug',0.25,50,
  ARRAY[['Amphibious','The bullywug can breathe air and water.'],['Speak with Frogs and Toads','The bullywug can communicate simple concepts to frogs and toads when it speaks in Bullywug'],['Swamp Camouflage','The bullywug has advantage on Dex (Stealth) checks made to hide in swampy terrain'],['Standing Leap','The bullywug''s long jump is up to 20 ft and its high jump is up to 10 ft, with or without a running start.']],
  ARRAY[['Multiattack','The bullywug makes two melee attacks: one with its bite and one with its spear.'],['Bite','Melee Weapon Attack: +3 to hit, reach 5ft, one target. Hit: (1d4 + 1) bludgeoning damage'],['Spear','Melee or Ranged Weapon Attack: +3 to hit, reach 5ft or range 20/60ft, one target. Hit: (1d6 + 1) piercing damage or (1d8 + 1) piercing damage if used with two hands to make a melee attack.']]),
  
  ('Cambion','Medium fiend, any evil alignment',
  '19 (scale mail)','11d8 + 33',
  30,null,null,60,null,
  18,4,18,4,16,3,14,2,12,1,16,3,
  'Str +7, Con +6, Int +5, Cha +6',
  'Deception +6, Intimidation +6, Perception +4, Stealth +7',
  null,'cold, fire, lightning, poison; bludgeoning, piercing, and slashing from nonmagical weapons',null,
  'Darkvision 60ft, passive Perception 14', 
  'Abyssal, Common, Infernal',5,1800,
  ARRAY[['Fiendish Blessing','The AC of the cambion includes its Charisma bonus'],['Innate Spellcasting',E'The cambion''s spellcasting ability is Charisma (spell save DC 14). The cambion can innately cast the following spells, requiring no material components:\n  3/day each: alter self, command, detect magic\n  1/day: plane shift (self only)']],
  ARRAY[['Multiattack','The cambion makes two melee attacks or uses its Fire Ray twice'],['Spear','Melee or Ranged Weapon Attack: +7 to hit, reach 5ft or range 20/60ft, one target. Hit: (1d6 + 4) piercing damage, or (1d8 + 4) piercing damage if used with two hands to make a melee attack, plus (1d6) fire damage.'],['Fire Ray','Ranged Spell Attack: +7 to hit, range 120ft, one target. Hit: (3d6) fire damage.'],['Fiendish Charm','One humanoid the cambion can see within 30 feet of it must succeed on a DC 14 Wis saving throw or be magically charmed for 1 day. The charmed target obeys the cambion''s spoken commands. If the target suffers any harm from the cambion or another creature or receives a suicidal command from the cambion, the target can repeat the saving throw, ending the effect on itself on a success. If a target''s saving throw is successful, or if the effect ends for it, the creature is immune to the cambion''s Fiendish Charm for the next 24 hours.']]),
  
  ('Carrion Crawler','Large monstrosity, unaligned',
  '13 (natural armor)','6d10 + 18',
  30,null,30,null,null,
  14,2,13,1,16,3,1,-5,12,1,5,-3,
  null,'Perception +3',null,null,null,
  'Darkvision 60ft, passive Perception 13',null,2,450,
  ARRAY[['Keen Smell','The carrion crawler has advantage on Wis (Perception) checks that rely on smell'],['Spider Climb','The carrion crawler can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check']],
  ARRAY[['Multiattack','The carrion crawler makes two attacks: one with its tentacles and one with its bite'],['Tentacles','Melee Weapon Attack: +8 to hit, reach 10ft, one creature. Hit: (1d4 + 2) poison damage, and the target must succeed on a DC 13 Con saving throw or be poisoned for 1 minute. Until this poison ends, the target or be poisoned for 1 minute. Until this poison ends, the target is paralyzed. The target can repeat the saving throw at the end of each of its turns, ending the poison on itself on a success.'],['Bite','Melee Weapon Attack: +4 to hit, reach 5ft, one target. Hit: (2d4 + 2) piercing damage']]),
  
  ('Centaur','Large monstrosity, neutral good',
  '12','6d10 + 12',50,null,null,null,null,
  18,4,14,2,14,2,9,-1,13,1,11,0,
  'Athletics +6, Perception +3, Survival +3',null,null,null,
  'passive Perception 13','Elvish, Sylvan',2,450,
  ARRAY[['Charge','If the centaur moves at least 30 feet straight toward a target and then hits it with a pike attack on the same turn, the target takes an extra (3d6) piercing damage.']],
  ARRAY[['Multiattack','The centaur makes two attacks: one with its pike and one with its hooves or two with its longbow.'],['Pike','Melee Weapon Attack: +6 to hit, reach 10ft, one target. Hit: (1d10 + 4) piercing damage.'],['Hooves','Melee Weapon Attack: +6 to hit, reach 5ft, one target. Hit: (2d6 + 4) bludgeoning damage.'],['Longbow','Ranged Weapon Attack: +4 to hit, range 150/600ft, one target. Hit: (1d8 + 2) piercing damage.']]),
  
  ('Chimera','Large monstrosity, chaotic evil','14 (natural armor)',
  '12d10 + 48',30,null,null,60,null,
  19,4,11,0,19,4,3,-4,14,2,10,0,
  null,'Perception +8',null,null,null,
  'Darkvision 60ft, passive Perception 18',
  'understands Draconic but can''t speak',6,2300,
  null,ARRAY[['Multiattack','The chimera makes three attacks: one with its bite, one with its horns, and one with its claws. When its fire breath is available, it can use the breath in place of its bite or horns.'],['Bite','Melee Weapon Attack: +7 to hit, reach 5ft, one target. Hit: (2d6 + 4) piercing damage.'],['Horns','Melee Weapon Attack: +7 to hit, reach 5ft, one target. Hit: (1d12 + 4) bludgeoning damage'],['Claws','Melee Weapon Attack: +7 to hit, reach 5ft, one target. Hit: (2d6 + 4) slashing damage'],['Fire Breath (Recharge 5-6)','The dragon head exhales fire in a 15-foot cone. Each creature in that area must make a DC 15 Dex saving throw, taking (7d8) fire damage on a failed save, or half as much damage on a successful one']]),
  
  ('Chuul','Large aberration, chaotic evil',
  '16 (natural armor)','11d10 + 33',
  30,null,null,null,30,
  19,4,10,0,16,3,5,-3,11,0,5,-3,
  null,'Perception +4',null,null,
  'poison; poisoned','Darkvision 60ft, passive Perception 14',
  'understands Deep Speech but can''t speak',4,1100,
  ARRAY[['Amphibious','The chuul can breathe air and water'],['Sense Magic','The chuul senses magic within 120ft of it at will. This trait otherwise works like the detect magic spell but isn''t itself magical']],
  ARRAY[['Multiattack','The chuul makes two pincer attack. If the chuul is grappling a creature, the chuul can also use its tentacles once.'],['Pincer','Melee Weapon Attack: +6 to hit, reach 10ft, one target. Hit: (2d6 + 4) bludgeoning damage. The target is grappled (escape DC 14) if it is a Large or smaller creature and the chuul doesn''t have two other creatures grappled.'],['Tentacles','One creature grappled by the chuul must succeed on a DC 13 Con saving throw or be poisoned for 1 minute. Until this poison ends, the target is paralyzed. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.']]),
  
  ('Cloaker','Large aberration, chaotic neutral',
  '14 (natural armor)','12d10 + 12',
  10,null,null,40,null,
  17,3,15,2,12,1,13,1,12,1,14,2,
  null,'Stealth +5',null,null,null,
  'Darkvision 60ft, passive Perception 11',
  'Deep Speech, Undercommon',8,3900,
  ARRAY[['Damage Transfer','While attached to a creature, the cloaker takes only half the damage dealt to it (rounded down), and that creature takes the other half.'],['False Appearance','While the cloaker remains motionless without its underside exposed, it is indistinguishable from a dark leather cloak'],['Light Sensitivity','While in bright light, the cloaker has disadvantage on attack rolls and Wis (Perception) checks that rely on sight.']],
  ARRAY[['Multiattack','The cloaker makes two attacks: one with its bite and one with its tail'],['Bite','Melee Weapon Attack: +6 to hit, reach 5 ft, one creature. Hit: (2d6 + 3) piercing damage, and if the target is Large or smaller, the cloaker attaches to it. lf the cloaker has advantage against the target, the cloaker attaches to the target''s head, and the target is blinded and unable to breathe while the cloaker is attached. While attached, the cloaker can make this attack only against the target and has advantage on the attack roll. The cloaker can detach itself by spending 5 feet of its movement. A creature, including the target, can take its action to detach the cloaker by succeeding on a DC 16 Strength check.'],['Tail','Melee Weapon Attack: +6 to hit, reach 10ft, one creature. Hit: (1d8 + 3) slashing damage.'],['Moan','Each creature within 60 feet of the cloaker that can hear its moan and that isn''t an aberration must succeed on a DC 13 Wisdom saving throw or become frightened until the end of the cloaker''s next turn. If a creature''s saving throw is successful, the creature is immune to the cloaker''s moan for the next 24 hours'],['Phantasms (Recharges after a Short or Long Rest)',E'The cloaker magically creates three illusory duplicates of itself if it isn''t in bright light. The duplicates move with it and mimic its actions, shifting position so as to make it impossible to track which cloaker is the real one. If the cloaker is ever in an area of bright light, the duplicates disappear.\n  Whenever any creature targets the cloaker with an attack or a harmful spell while a duplicate remains, that creature rolls randomly to determine whether it targets the cloaker or one of the duplicates. A creature is unaffected by this magical effect if it can''t see or if it relies on senses other than sight.\n  A duplicate has the cloaker''s AC and uses its saving throws. If an attack hits a duplicate, or if a duplicate fails a saving throw against an effect that deals damage, the duplicate disappears.]]),
  
  ('Cockatrice','Small monstrosity, unaligned',
  '11','6d6 + 6',20,null,null,40,null,
  6,-2,12,1,12,1,2,-4,13,1,5,-3,
  null,null,null,null,null,
  'Darkvision 60ft, passive Perception 11',
  null,0.5,100,
  null,ARRAY[['Bite','Melee Weapon Attack: +3 to hit, reach 5 ft, one creature. Hit: (1d4 + 1) piercing damage, and the target must succeed on a DC 11 Con saving throw against being magically petrified. On a failed save, the creature begins to turn to stone and is restrained. It must repeat the saving throw at the end of its next turn. On a success, the effect ends. On a failure, the creature is petrified for 24 hours.']]),
  
  ('Couatl','Medium celestial, lawful good',
  '19 (natural armor)','13d8 + 39',
  30,null,null,90,null,
  16,3,20,5,17,3,18,4,20,5,18,4,
  'Con +5, Wis +7, Cha +6',null,null,
  'radiant','psychic; bludgeoning, piercing, and slashing from nonmagical weapons',
  'Truesight 120ft, passive Perception 15',
  'All, telepathy 120ft',4,1100,
  ARRAY[['Innate Spellcasting',E'The couatl''s spellcasting ability is Cha (spell save DC 14). It can innately cast the following spells, requiring only verbal components:\n  At will: detect evil and good, detect magic, detect thoughts\n  3/day each: bless, create food and water, cure wounds, lesser restoration, protection from poison, sanctuary, shield\n  1/day each: dream, greater restoration, scrying'],['Magic Weapons','The couratl's weapon attacks are magical'],['Shielded Mind','The couatl is immune to scrying and to any effect that would sense its emotions, read its thoughts, or detect its location']],
  ARRAY[['Bite','Melee Weapon Attack: +8 to hit, reach 5ft, one creature. Hit: (1d6 + 5) piercing damage, and the target must succeed on a DC 13 Con saving throw or be poisoned for 24 hours. Until this poison ends, the target is unconscious. Another creature can use an action to shake the target awake.'],['Constrict','Melee Weapon Attack: +6 to hit, reach 10ft, one Medium or smaller creature. Hit: (2d6 + 3) bludgeoning damage, and the target is grappled (escape DC 15). Until this grapple ends, the target is restrained, and the couatl can''t constrict another target.'],['Change Shape',E'The couatl magically polymorphs into a humanoid or beast that has a challenge rating equal to or less than its own, or back into its true form. It reverts to its true form if it dies. Any equipment it is wearing or carrying is absorbed or borne by the new form (the couatl''s choice).\n  In a new form, the couatl retains its game statistics and ability to speak, but its AC, movement modes, Strength, Dexterity, and other actions are replaced by those of the new form, and it gains any statistics and capabilities (except class features, legendary actions, and lair actions) that the new form has but that it lacks . If the new form has a bite attack, the couatl can use its bite in that form.']]),
  
  ('Crawling Claw','Tiny undead, neutral evil',
  '12','1d4',
  20,null,20,null,null,
  13,1,14,2,11,0,5,-3,10,0,4,-3,
  null,null,null,null,'poison; charmed, exhaustion, poisoned',
  'Blindsight 30ft (blind beyond this radius), passive Perception 10',
  'understands Common but can''t speak',0,10,
  ARRAY[['Turn Immunity','The claw is immune to effects that turn undead']],
  ARRAY[['Claw','Melee Weapon Attack: +3 to hit, reach 5ft, one target. Hit: (1d4 + 1) bludgeoning or slashing damage (claw''s choice)']]),
  
  ('Cyclops','Huge giant, chaotic neutral',
  '14 (natural armor)','12d12 + 60',
  30,null,null,null,null,
  22,6,11,0,20,5,8,-1,6,-2,10,0,
  null,null,null,null,null,
  'passive Perception 8','Giant',6,2300,
  ARRAY[['Poor Depth Perception','The cyclops has disadvantage on any attack roll against a target more than 30ft away']],
  ARRAY[['Multiattack','The cyclops makes two greatclub attacks'],['Greatclub','Melee Weapon Attack: +9 to hit, reach 10ft, one target. Hit: (3d8 + 6) bludgeoning damage'],['Rock','Ranged Weapon Attack: +9 to hit, range 30/120ft, one target. Hit: (4d10 + 6) bludgeoning damage']]);
  
  
  
COMMIT
  -- ('Name',
  -- 'Type, alignment',
  -- 'AC# (mods)',
  -- 'xdy + z',
  -- Speed,Burrow Speed,Climb Speed,Flight Speed,Swim Speed,
  -- str,strmod,dex,dexmod,con,conmod,int,intmod,wis,wismod,cha,chamod,
  -- 'saving throws',
  -- skills,
  -- vulnerabilities,
  -- resistances,
  -- 'immunities',
  -- 'senses',
  -- 'languages',
  -- CR,
  -- XP,
  -- Abilities/properties: ARRAY[['Heated Body','A creature that touches the azer or hits it with a melee attack while within 5 feet of it takes (1d10) fire damage.'], ['Heated Weapons','When the azer hits with a metal melee weapon, it deals an extra (1d6) fire damage (included in the attack).'], ['Illumination','The azer sheds bright light in a 10-foot radius and dim light for an additional 10 feet.'], ['Living Fire','An azer doesn''t require food, drink, or sleep.']],
  -- Attacks: ARRAY[['Warhammer','Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: (1d8 + 3) bludgeoning damage, or (1d10 + 3) bludgeoning damage if used with two hands to make a melee attack, plus (1d6) fire damage.']]),